@startuml Agent-Environment Interaction

!theme plain
skinparam backgroundColor #FFFFFF
scale 2
title Agent-Environment Interaction

(*) --> "reset environment"
-down-> "select action"
-right-> [take action] "step environment"
--> [observe experience] "update agent"
if "reached total global time steps" then
--> [true] (*)
else
--> [false] "select action"

@enduml