@startuml Policy Gradient Training

!theme plain
skinparam backgroundColor #FFFFFF
scale 2
title Policy Gradient Training

(*) --> "sample experience batch"
--> "compute reinforce singal (e.g., advantage)"
--> "compute policy loss"
--> "gradient step"
--> (*)

@enduml