CartPole-v1_A2C:
  Env:
    type: Gym
    Config:
      id: CartPole-v1
  Train:
    num_envs: 3
    seed: 0
    Config:
      time_steps: 20000
      summary_freq: 1000
  Inference:
    seed: 0
    Config:
      episodes: 3
      export: render_only
  Agent:
    n_steps: 16