CartPole-v1_REINFORCE:
  Env:
    type: Gym
    Config:
      id: CartPole-v1
  Train:
    Config:
      time_steps: 200000
  Inference:
    Config:
      episodes: 10
      export: render_only
  Agent:
    gamma: 0.99
    entropy_coef: 0.001