CartPole-v1-NoVelocity_RecurrentPPO:
  Train:
    num_envs: 16
    seed: 0
    Config:
      time_steps: 100000
      summary_freq: 2000
  Inference:
    seed: 0
    Config:
      episodes: 3
      export: render_only
  Agent:
    n_steps: 256
    epoch: 4
    seq_len: 16
    seq_mini_batch_size: 16