CartPole-v1_DoubleDQN:
  Env:
    type: Gym
    Config:
      id: CartPole-v1
  Train:
    num_envs: 3
    seed: 0
    Config:
      time_steps: 20000
      summary_freq: 1000
  Inference:
    seed: 0
    Config:
      episodes: 3
      export: render_only
  Agent:
    n_steps: 16
    batch_size: 128
    capacity: 1000
    epoch: 3
    replace_freq: 12