CartPole-v1_PPO:
  Env:
    type: Gym
    Config:
      id: CartPole-v1
  Train:
    num_envs: 3
    Config:
      time_steps: 10000
      summary_freq: 500
  Inference:
    Config:
      episodes: 10
      export: render_only
  Agent:
    n_steps: 16
    epoch: 3
    mini_batch_size: 8
    gamma: 0.99
    lam: 0.95
    advantage_normalization: false
    epsilon_clip: 0.2
    value_loss_coef: 0.5
    entropy_coef: 0.001