CartPole-v1_DoubleDQN:
  num_envs: 3
  Gym:
    env:
      id: "CartPole-v1"
    training:
      seed: 0
      auto_retrain: true
      total_global_time_steps: 150000
      summary_freq: 1000
      agent_save_freq: null
      inference_freq: 10000
      inference_render: true
  DoubleDQN:
    training_freq: 16
    batch_size: 128
    capacity: 1000
    epoch: 3
    gamma: 0.99
    replace_freq: 12
    grad_clip_max_norm: 5.0
