CartPole-v1_RecurrentPPO:
  num_envs: 3
  Gym:
    env:
      id: "CartPole-v1"
    training:
      seed: 0
      auto_retrain: false
      total_global_time_steps: 150000
      summary_freq: 1000
      agent_save_freq: null
      inference_freq: null
      inference_render: false