CartPole-v1_REINFORCE:
  num_envs: 1
  Gym:
    env:
      id: "CartPole-v1"
    training:
      seed: 0
      auto_retrain: true
      total_global_time_steps: 150000
      summary_freq: 1000
      agent_save_freq: null
      inference_freq: 10000
      inference_render: true
  REINFORCE:
    gamma: 0.99
    entropy_coef: 0.001
    grad_clip_max_norm: 5.0