remote_theme: rundocs/jekyll-rtd-theme

# folders sort
readme_index:
  with_frontmatter: true

mathjax: # this will prased to json, default: {}

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
